<?php

/**
 * @file
 * Contains wizfish_d8_template.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function wizfish_d8_template_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the wizfish_d8_template module.
    case 'help.page.wizfish_d8_template':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Template Drupal 8 module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function wizfish_theme() {
  return [
    'wizfish_d8_template' => [
      'render element' => 'children',
    ],
  ];
}
