<?php

/**
 * @file
 * Contains wizfish_d8_template.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_entity_view().
 */

function wizfish_d8_template_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $$
  // This hook will be called everytime any entity is viewed.
  drupal_set_message(t('All is as it should be! Carry on partner.'), 'status');

  if($entity->getEntityType()->id() === 'node') {
    $build['awesome'] = [
      '#markup' => '<marquee>This is awesome.</marquee>',
      '#allowed_tags' => ['marquee'],
    ];
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */

//function wizfish_d8_template_node_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $$
  // This hook will be called everytime any entity is viewed.
//  drupal_set_message(t('All is as it should be! Carry on partner.'), 'status');
//
//  $build['terrific'] = [
//    '#markup' => '<marquee>This is terrific.</marquee>',
//    '#allowed_tags' => ['marquee'],
//  ];
//}

/**
 * Implements hook_help().
 */
function wizfish_d8_template_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the wizfish_d8_template module.
    case 'help.page.wizfish_d8_template':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Template Drupal 8 module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function wizfish_theme() {
  return [
    'wizfish_d8_template' => [
      'render element' => 'children',
    ],
  ];
}
